### PR TITLE
Remove aliases

### PR DESCRIPTION
**Pull request by 202291**
# Removed all unused and metric vs imperial aliases

This includes
- anything containing `tre` was removed due to enums using `ter` only. (e.g. `['metre', 'meter']` is now just `['meter']`
- removed references to `unit-ali.json` in favor of `Units.js`
- changed definitions to be in favor of `Units.js`
- left shorthand strings alone in case the owner does decide to include them in enums (please don't)

```js
- 202291
````

### CODE REVIEW

**Comment by Yetity** [comment]
Why is `centiliter` `centiiter`?

**Comment by 202291** [comment]
mistake lol

**Review by yetnt — APPROVED** [review]
forgor one more thing, but i can fix that later.

**Review by yetnt — COMMENTED** [review]
forgot a review

**Pull request merged**
